name = "hello-__APP_TYPE__"
description = "Hello World Ruby Server"

internal = true

image = "precise64"
app_type = "__APP_TYPE__"

run_commands = ["./app.rb"]

dependencies = []

cpu_shares = 5
memory_limit = 128
