name = "hello-go"
description = "Hello World Go Server"

internal = true

image = "precise64"
app_type = "__APP_TYPE__"

run_commands = ["./hello"]

dependencies = []

cpu_shares = 5
memory_limit = 128
